# The following variables have to be defined in the GUI
# of the Drone Buildserver
#
# RPI_IMAGE_BUILDER_ROOT: /builder
# BUILD_RESULTS: /build_result
#
# For uploading the build results to Amazon S3
# we need the follwing Amazon S3 credentials
#
# AWS_ACCESS_KEY_ID: your_aws_key
# AWS_SECRET_ACCESS_KEY: your_secret_access_key
#
image: hypriot/builder_base

git:
  path: github.com/hypriot/rpi-image-builder

script:
  - mkdir -p /tmp/cache/apt/lists/partial /tmp/cache/apt/archives/partial
  - ls -lah /tmp/cache/apt/archives/**
  - echo "dir::cache::archives /tmp/cache/apt;" > /etc/apt/apt.conf
  - echo "dir::state::lists /tmp/cache/apt/lists;" >> /etc/apt/apt.conf
  - printenv
  - scripts/prepare_build_environment.sh
  - service apt-cacher-ng start
  - service binfmt-support start
  - scripts/fetch_build_inputs.sh
  - scripts/build_image.sh
  - tree /tmp/cache -L 6


publish:
  s3:
    acl: public-read
    region: eu-central-1
    bucket: buildserver-production
    access_key: $$AWS_ACCESS_KEY_ID
    secret_key: $$AWS_SECRET_ACCESS_KEY
    source: $$BUILD_RESULTS/
    target: images/
    recursive: true

cache:
  - /tmp/cache
