#!/bin/bash

# configuration for all build scripts
KERNEL_DATETIME=${KERNEL_DATETIME:="20150906-092404"}
KERNEL_VERSION=${KERNEL_VERSION:="4.1.6"}

DOCKER_DEB=${DOCKER_DEB:="docker-hypriot_1.8.1-1_armhf.deb"}

SD_CARD_SIZE="1400"        # "1400" = approx. 1.4 GB
BOOT_PARTITION_SIZE="64"   # "64" = 64 MB

_DEB_RELEASE="jessie"					# stable | testing | unstable | jessie | wheezy | squeeze, ...
_APT_SOURCE="${_APT_SOURCE_RASPBIAN}"

_APT_PACKAGES="locales console-common openssh-server ntp less vim ntpdate fake-hwclock occi avahi-daemon usbutils htop apt-transport-https"

_HOSTNAME="black-pearl"
_NET_CONFIG="dhcp"

_USER_NAME="root"
_USER_PASS="hypriot"

_KEYMAP="us"
_TIMEZONE="Europe/Berlin"
_LOCALES="en_US"
_ENCODING="UTF-8"
