#!/bin/bash

# configuration for all build scripts
KERNEL_DATETIME=${KERNEL_DATETIME:="20160212-075712"}
KERNEL_VERSION=${KERNEL_VERSION:="4.1.17"}

DOCKER_DEB=${DOCKER_DEB:="docker-hypriot_1.10.2-1_armhf.deb"}
DOCKER_COMPOSE_VERSION=${DOCKER_COMPOSE_VERSION:="1.6.2-28"}
DOCKER_MACHINE_VERSION=${DOCKER_MACHINE_VERSION:="0.4.1-72"}
DOCKER_SWARM_VERSION=${DOCKER_SWARM_VERSION:="1.1.3"}

SD_CARD_SIZE="1700"        # "1700" = approx. 1.7 GB
BOOT_PARTITION_SIZE="64"   # "64" = 64 MB

_DEB_RELEASE="jessie"					# stable | testing | unstable | jessie | wheezy | squeeze, ...
_APT_SOURCE="${_APT_SOURCE_RASPBIAN}"

_APT_PACKAGES="locales console-common openssh-server ntp less vim ntpdate fake-hwclock occi avahi-daemon usbutils htop apt-transport-https \
               firmware-atheros firmware-brcm80211 firmware-libertas firmware-ralink firmware-realtek"

_HOSTNAME="black-pearl"
_NET_CONFIG="dhcp"

_USER_NAME="root"
_USER_PASS="hypriot"

_KEYMAP="us"
_TIMEZONE="Europe/Berlin"
_LOCALES="en_US"
_ENCODING="UTF-8"
